### ISSUE TITLE
Lakes a tad too plentiful in Metal Renegades, and lacking palm trees?

### ISSUE THREAD

**Issue by Cervator** [Terasology/Lakes#10]
I'm not sure if the biome setup differs in Metal Renegades, but when I tried it for a play test this is how it turned out:

https://cdn.discordapp.com/attachments/702893102481932308/751859600994861066/unknown.png

Lakes _everywhere_ and not sure if oasis-style or not as I couldn't find any palm trees at all. This was specifically in multiplayer so I'm not sure if there were any quirks just preventing me from seeing the palms due to block id weirdness

At the least we probably need to vary the lake probability (maybe that can be done specifically in MR, akin to how you can for instance vary the spawn rates for WildAnimals from a module depending on it?), hopefully can also look at the palm situation

**Comment by jdrueckert** [comment]
I believe when I looked at it in JS the amount of lakes was fine, but there were no palm trees as well.

**Comment by skaldarnar** [comment]
Resolved by #14. Further work on re-enabling world-gen config will help to tweak this even better from game modes.
