### ISSUE TITLE
Lakes need to be identifiable somehow to other world features spawning later

### ISSUE THREAD

**Issue by Cervator** [Terasology/Lakes#12]
Pretty similar to #9 and odds are this will need a fix elsewhere, but I'm not sure how lakes at present makes their existence clear in a way that other systems can check.

Metal Renegades drawback example: https://cdn.discordapp.com/attachments/702893102481932308/751860400575873043/unknown.png

That's a former lake, that generated in the desert wasteland in Metal Renegades, where a city then decided to start spawning stuff on top. That's powered by the system in Dynamic Cities which seems to just be going by the natural contours of the terrain, even after the lake made a hollow to fill with water.

To replicate simply start Metal Renegades + Lakes and look for a city to spawn by one or more lakes. May need to tweak spawn probabilities of either cities or lakes to find a good example, this screenie is from my first attempt though so it may be common (at least until lake probabilities for MR get turned down)

**Comment by skaldarnar** [comment]
The described bug is "fixed" if all involved generators check the new `SurfacesFacet` instead of just working with elevation data. Lakes, like other features, can modify the surfaces facet to remove areas that are blocked by them.
