### ISSUE TITLE
Need another code style / quality pass

### ISSUE THREAD

**Issue by Cervator** [Terasology/Lakes#7]
The project code style guidelines changed quite a bit since Lakes was created (not sure we even *had* a guide back then!) and while #6 helped with some of them we could use another pass with special attention paid to magic numbers.

While at it maybe also consider https://github.com/Terasology/Lakes/pull/6/files#r467456467 to see if that could be refactored in

Also spotted a couple AWT uses (rectangles and polygons) now that we're trying to use JOML maybe there are analogues over there to use instead?

On a not really quality angle but I wanted to mention it somewhere there are two ways in which the lakes themselves could probably be improved:

* Trees may spawn on top of lakes / lakes may spawn below trees. Possible to remove the trees, but tricky ...
* Desert lakes don't seem to clear off sand blocks if more than 2-3 blocks above the water level (but hey maybe it is sandstone..)

**Comment by skaldarnar** [comment]
#14 did more or less a rewrite of the module, improving both code style and general quality.
