### ISSUE TITLE
Have placed lakes clean up leftover blocks and flora above them

### ISSUE THREAD

**Issue by Cervator** [Terasology/Lakes#9]
Not necessarily an easy task and a common one to other world features as well. Two particular parts to it:

1. When a lake is placed grass and trees may remain (or generate after the lake) immediately or a block above the water
1. On inclines floating blocks may be left in place that should probably be deleted much like blocks _immediately_ above the water - except if they're in a well-integrated surface like a cave roof. Mostly looking at one block thing slices left behind with gently sloping terrain, but this is again likely difficult to properly identify and balance

![image](https://user-images.githubusercontent.com/1063833/92192775-5dece780-ee2c-11ea-9ba4-9e1bb4d79487.png)

**Comment by jdrueckert** [comment]
I believe we had that same issue with Caves before. I would have thought that with https://github.com/Terasology/CoreWorlds/pull/6 this shouldn't happen for water, but maybe water has "supporting" properties :thinking:

**Comment by skaldarnar** [comment]
Fixed by #14
